controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: false  # Important: Set to false for real hardware
    
    # Controllers to load and start
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    ackermann_controller:
      type: ackermann_steering_controller/AckermannSteeringController
      
    imu_broadcaster:
      type: imu_sensor_broadcaster/ImuSensorBroadcaster
      
    range_sensor_broadcaster:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - steering_joint
      - back_left_wheel_joint
      - back_right_wheel_joint
      - front_left_wheel_joint
      - front_right_wheel_joint

# Ackermann Steering Controller Configuration
ackermann_controller:
  ros__parameters:
    # Interface names - Updated for correct joint assignment
    front_steering_joints: ["steering_joint"]
    rear_wheels_joints: ["back_left_wheel_joint", "back_right_wheel_joint"]
    
    # Physical parameters (adjust these to match your robot)
    wheelbase: 0.14              # Distance between front and rear axles (m)
    front_wheel_track: 0.175     # Distance between front wheels (m)
    rear_wheel_track: 0.175      # Distance between rear wheels (m) 
    wheel_radius: 0.05           # Wheel radius (m)
    
    # Controller parameters
    reference_timeout: 2.0       # Time to wait for command before stopping
    publish_rate: 50.0
    publish_wheel_data: true
    publish_ackermann_command: true
    
    # Twist message interface
    use_stamped_vel: false
    
    # Frame names
    base_frame_id: base_link
    odom_frame_id: odom

# IMU Sensor Broadcaster Configuration  
imu_broadcaster:
  ros__parameters:
    sensor_name: imu_sensor
    frame_id: imu_link

# Range Sensor Broadcaster Configuration
range_sensor_broadcaster:
  ros__parameters:
    sensors:
      - sensor_name: tf_luna_front
        frame_id: tf_luna_front_link
        topic_name: /tf_luna_front/range
      - sensor_name: tf_luna_left  
        frame_id: tf_luna_left_link
        topic_name: /tf_luna_left/range
      - sensor_name: tf_luna_right
        frame_id: tf_luna_right_link
        topic_name: /tf_luna_right/range
